name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Install DFX"
      run: |
        wget -O install-dfx.sh https://sdk.dfinity.org/install.sh
        yes Y | DFX_VERSION=0.6.0 bash install-dfx.sh
        echo "::add-path::/home/runner/bin"
    - name: "Install DFX Cache"
      run: dfx cache install
    - name: "Install Vessel"
      run: |
        wget -O /home/runner/bin/vessel https://github.com/kritzcreek/vessel/releases/download/v0.4.1/vessel-linux64
        chmod +x /home/runner/bin/vessel
    - name: "Run Demo Script"
      run: ./demo.sh
